

# Generated By Gpt


import numpy as np
import matplotlib.pyplot as plt


#  Basic Syntax
x, y1, y2 = 0, 0, 0
plt.stackplot(x, y1, y2, ..., labels=..., colors=...,
              alpha=..., baseline=...)

#  Key Parameters

# Parameter	Description

# x	1D array-like: The x-axis values.

# y1, y2, ...	1D array-like: The data series to stack(must match the shape of x).

# labels	List of strings: Labels for each series(used with legend).

# colors	List of colors for the individual plots.

# alpha	Float: Transparency of the plot(0.0 to 1.0).

# baseline	String: Controls the baseline. Options include 'zero', 'sym', 'wiggle', 'weighted_wiggle'.

# **kwargs	Additional keyword arguments passed to fill_between().

#  Styling Options

# All styling supported by fill_between() also works in stackplot. Some examples:

#   linewidth: Line thickness

#   edgecolor: Color of the borders

#    linestyle: Line style(solid, dashed, etc.)

#   zorder: Layering of the plot

#  hatch: Patterns like stripes, dots

#  Baseline Options(Stacking Strategy)

# 'zero': Default, stacks from the x-axis.

# 'sym': Symmetric around a central line.

# 'wiggle': Minimizes changes in slope(stream graph style).

# 'weighted_wiggle': Like wiggle, but weighted by area.

#  Typical Use Example


x = np.arange(5)
y1 = np.array([1, 3, 4, 2, 1])
y2 = np.array([2, 2, 3, 2, 2])
y3 = np.array([3, 4, 1, 3, 3])

plt.stackplot(x, y1, y2, y3,
              labels=['A', 'B', 'C'],
              colors=['#1f77b4', '#ff7f0e', '#2ca02c'],
              alpha=0.8,
              baseline='zero')

plt.legend(loc='upper left')
plt.title("Stack Plot Example")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.grid(True)
plt.show()

# Extra Tips

# Use plt.legend() for labeling.

# To animate stackplots, combine with FuncAnimation.

# Stackplots are ideal for showing part-to-whole relationships over time.


# Sample data
x = np.arange(2000, 2010)
A = np.array([1, 2, 4, 6, 7, 8, 6, 4, 3, 2])
B = np.array([2, 3, 3, 2, 1, 2, 4, 6, 7, 8])
C = np.array([3, 2, 1, 1, 2, 2, 3, 3, 2, 1])

# Create the streamgraph-like stackplot
plt.figure(figsize=(10, 6))
plt.stackplot(x, A, B, C,
              labels=['Apples', 'Bananas', 'Cherries'],
              colors=['#8dd3c7', '#ffffb3', '#bebada'],
              alpha=0.9,
              baseline='wiggle')

# Add labels and legend
plt.title("Streamgraph Example with baseline='wiggle'")
plt.xlabel("Year")
plt.ylabel("Value")
plt.legend(loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()
